//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ItemObject
{
    private Texture2D sprite;
    private string name;
    private int quantity;

    public ItemObject(Texture2D sprite)
    {
    }

    public Texture2D Sprite
    {
        get
        {
            return sprite;
        }
        set
        {
            sprite = value;
        }
    }

    public string Name
    {
        get
        {
            return name;
        }
        set
        {
            name = value;
        }
    }
}

