//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ItemObject
{
    private Texture2D sprite;
    private string name;
    private int quantity;

    public ItemObject()
    {

    }

    public ItemObject(Texture2D sprite, string name)
    {
        this.sprite = sprite;
        this.name = name;
    }

    public Texture2D Texture
    {
        get
        {
            return sprite;
        }
        set
        {
            sprite = value;
        }
    }

    public string Name
    {
        get
        {
            return name;
        }
        set
        {
            name = value;
        }
    }

    public void AddItem()
    {
        quantity++;
    }

    public bool UseItem()
    {
        if (quantity > 0)
        {
            quantity--;
            return true;
        }
        else
        {
            return false;
        }
    }

    public int Count
    {
        get
        {
            return quantity;
        }
        set
        {
            quantity = value;
        }
    }
}

